### ISSUE TITLE
algokit init doesn't use active python version with poetry + pyenv

### ISSUE THREAD

**Issue by joe-p** [algorandfoundation/algokit-cli#165] opened 2023-01-28 14:27 UTC
If installing algokit on a system with pyenv, poetry will not detect the current active version of Python by default. This means the installation of the dependencies might occur on the incorrect version of Python. 

To fix this, part of the init process could ask if pyenv should be configured with `poetry config virtualenvs.prefer-active-python true` to automatically detect the active version of Python

**Comment by robdmoore** [comment] 2023-02-09 09:55
Thoughts @achidlow?

**Comment by robdmoore** [comment] 2023-02-09 10:29
@joe-p I've set that to be the default now in the template. Can you give it a go?

**Comment by robdmoore** [comment] 2023-02-09 10:32
Thinking about it, the other option rather than relying on the template to configure this is we could make the algokit bootstrap command automatically issue this command, but the downside is that it wouldn't be possible to easily opt out of that behaviour then.

**Comment by abebeos** [comment] 2023-03-31 11:58
@robdmoore from my understanding, [9985005](https://github.com/algorandfoundation/algokit-beaker-default-template/commit/9985005b7389c90c6afed685d75bb8e7608b2a96) should have fixed this.



> @joe-p I've set that to be the default now in the template. Can you give it a go?

@joe-p ?

**Comment by robdmoore** [comment] 2023-04-02 01:51
Joe - actually in the end we needed to remove this flag because it broke things.

I’m a bit unclear on when this flag should be added to make things work. Can we detect the need for it? Asking about pyenv is likely to confuse people unfamiliar with python.

**Comment by abebeos** [comment] 2023-04-02 13:25
> Asking about pyenv is likely to confuse people unfamiliar with python.

+1

> I’m a bit unclear on when this flag should be added to make things work.

As an advanced user, I would expect that no version mismatch happens, and that algokit works out of the box on my system.

So, if this is a reproduced https://github.com/algorandfoundation/algokit-cli/labels/bug, then it needs to be fixed.

If you do this based on this flag, or based on e.g. a global var initialized to the system python version? Don't know. But it needs to be fixed, I guess.

### Question

@robdmoore , where does the init process gets the python version to be used from? Possibly at this location you query the sys-version and assign it.

**Comment by robdmoore** [comment] 2023-04-02 15:08
The problem isn't with algokit itself, it uses the expected python version (here's the check by the way: https://github.com/algorandfoundation/algokit-cli/blob/main/src/algokit/__init__.py#L4).

The problem is when `poetry install` is called as part of bootstrapping a project.

**Comment by joe-p** [comment] 2023-04-02 15:09
I think this is really a bug with VSCode not properly being able to make sense of what the interpreter should be. I also can't seem to 100% reproduce it and even with the above setting it sometimes didn't work. 

Worth mentioning I'm using asdf to install python, so that could be part of the problem. Next time I run into an issue I will spend more time debugging.

**Comment by robdmoore** [comment] 2023-04-22 06:01
Cool, will close in meantime. Feel free to re-open if you reproduce.

**Closed by robdmoore** 2023-04-22 06:01 UTC
Labels: bug
