### ISSUE TITLE
Error compiling "init" sample smart contracts

### ISSUE THREAD

**Issue by MrJackdaw** [algorandfoundation/algokit-cli#161] opened 2023-01-21 15:37 UTC
Hello all; please let me know if this is something I should take up with `Beaker`.

### Command run
`python -m smart_contracts`

### Error output
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/[~~REDACTED~~]/newtoast/smart_contracts/__main__.py", line 3, in <module>
    from smart_contracts.lab import my_lab
  File "/[~~REDACTED~~]/newtoast/smart_contracts/lab.py", line 29, in <module>
    apps=[HelloWorld()],
          ^^^^^^^^^^^^
  File "/[~~REDACTED~~]/newtoast/.venv/lib/python3.11/site-packages/beaker/application.py", line 241, in __init__
    self.compile()
  File "/[~~REDACTED~~]/newtoast/.venv/lib/python3.11/site-packages/beaker/application.py", line 280, in compile
    ) = self.router.compile_program(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/[~~REDACTED~~]/newtoast/.venv/lib/python3.11/site-packages/pyteal/ast/router.py", line 746, in compile_program
    ap_compiled = compileTeal(
                  ^^^^^^^^^^^^
  File "/[~~REDACTED~~]/newtoast/.venv/lib/python3.11/site-packages/pyteal/compiler/compiler.py", line 279, in compileTeal
    compileSubroutine(
  File "/[~~REDACTED~~]/newtoast/.venv/lib/python3.11/site-packages/pyteal/compiler/compiler.py", line 152, in compileSubroutine
    start, end = ast.__teal__(options)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/[~~REDACTED~~]/newtoast/.venv/lib/python3.11/site-packages/pyteal/ast/cond.py", line 82, in __teal__
    condStart, condEnd = cond.__teal__(options)
                         ^^^^^^^^^^^^^^^^^^^^^^
  File "/[~~REDACTED~~]/newtoast/.venv/lib/python3.11/site-packages/pyteal/ast/binaryexpr.py", line 39, in __teal__
    self.op.min_version,
    ^^^^^^^^^^^^^^^^^^^
  File "/[~~REDACTED~~]/newtoast/.venv/lib/python3.11/site-packages/pyteal/ir/ops.py", line 31, in min_version
    return self.value.min_version
           ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'tuple' object has no attribute 'min_version'
```

### Background
- I successfully installed the kit, and used the [init](https://github.com/algorandfoundation/algokit-cli/blob/main/docs/features/init.md) command to generate a sample project. 
- I ran the above command `python -m smart_contracts` in the project's root directory
- No modifications were made to the original `init` files. 

### Additional Notes
- I could not find a reference to a `min_version` in the Beaker `Application` class
- I may be doing something obviously wrong, but haven't found documentation (in Beaker, PyTeal, or the Algorand forum) that indicates this. 
- Please add documentation that you are using [`Beaker`](https://algorand-devrel.github.io/beaker/html/index.html). As a new user, it took me too long (and much frustration) to eventually discover that **PyTeal** and **Beaker** are different things.

**Comment by barnjamin** [comment] 2023-01-21 15:54
This is caused by a change in python 3.11, for the moment you can run `poetry env use 3.10`

Beaker master has the changes to incorporate pyteal 0.21.0 which has the fix, should be released Monday.

**Comment by MrJackdaw** [comment] 2023-01-21 17:39
Cheers for the response! Please, feel free to close this issue: I will create a new one if i encounter anything else.

**Comment by barnjamin** [comment] 2023-01-21 17:42
No sweat, I'll leave it open until its fixed so other folks don't have to dig as far

**Comment by barnjamin** [comment] 2023-01-23 19:46
Should be all set now, closing

**Closed by barnjamin** 2023-01-23 19:46 UTC
